# ASIATIC OPTION PRICING


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf







## DEFINE PARAMETERS

In [14]:
# PARAMETERS
M = 100 # number of simulation by the M.C method
T = 1 # maturity
K = 270.0
S0 = 250.0 
r = 0.035 
sigma = 0.03 
n = 1000 # number of values to get to compute the mean of S
dt = T / n






## RANDOM WALKING : PRICE SIMULATION

In [ ]:
np.random.seed(42) # the number of life
S = -1.0 * np.ones((M,n)) # initialization of the matrix
S[:,0] = S0



[[250.  -1.  -1. ...  -1.  -1.  -1.]
 [250.  -1.  -1. ...  -1.  -1.  -1.]
 [250.  -1.  -1. ...  -1.  -1.  -1.]
 ...
 [250.  -1.  -1. ...  -1.  -1.  -1.]
 [250.  -1.  -1. ...  -1.  -1.  -1.]
 [250.  -1.  -1. ...  -1.  -1.  -1.]]
